### ISSUE TITLE
Nested annotations in @method

### ISSUE THREAD

**Issue by mindplay-dk** [phpDocumentor/fig-standards#103]
Can we allow nested annotations in `@method`? (or is it already allowed? the section on `@method` in the current spec doesn't mention it.)

This would enable much more detailed descriptions of virtual methods, e.g.:

```
/**
 * @method bar {
 *     Room for documentation here
 *     @param string $foo more detailed param description here
 *     @return detailed return value description here
 * }
 */
class Foo { ... }
```

**Comment by e1himself** [comment]
Hi!

Here I raised another issue regarding overloading functions:
https://github.com/phpDocumentor/fig-standards/issues/82

Though my suggested approach is different, issues are obviously related.

**Comment by mvriel** [comment]
We can expand the @method section to mention that instead of a simple description you can use an Inline PHPDoc to document the details on a method. Don't see why not, excellent suggestion :)

**Comment by e1himself** [comment]
+1

**Comment by mindplay-dk** [comment]
Perhaps related or separate issue, not sure, but the section on [inline php-doc](https://github.com/phpDocumentor/fig-standards/blob/master/proposed/phpdoc.md#54-inline-phpdoc) actually uses `@method` as the example of using inline doc-blocks.

Perhaps this example should be moved to the section on `@method`?

It would seem silly to repeat it - maybe it could just say something like "see documentation for `@method`" and link to the example instead?

**Comment by Setitch** [comment]
+1 - i lately needed that very very much - but it failed (couldnt do it at all)

**Comment by ashnazg** [comment]
Looks like this just needs to be added in the tag's section.

**Comment by neuro159** [comment]
Well. It will also need to be supported )

Is there other cases for such a syntax? it would be not nice to have ton of special cases...
We see `(..)` for attrs, `<...>` for parametrised types and now this...

**Comment by jaapio** [comment]
I do agree that we need to try to keep the number of variant small. For all tools it will be a pain to have all kinds of notations, but it will also make you it harder for developers writing php how to notate docblocks.

I think we should try to collect all variants and try to reduce them.

**Comment by ashnazg** [comment]
Does that imply that we should _**remove**_ the *"Inline PHPDoc"* concept altogether?

**Comment by e1himself** [comment]
> Is there other cases for such a syntax? it would be not nice to have ton of special cases... We see (..) for attrs, <...> for parametrised types and now this...

Do you guys think it would make sense to use spaces indentation only: 

```
/**
 * @method bar
 *     Room for documentation here
 *     @param string $foo more detailed param description here
 *     @return detailed return value description here
 */
```

or is it too alien for a C-style language?

**Comment by neuro159** [comment]
>Do you guys think it would make sense to use spaces indentation only?

Please no - although we have pretty impressive Python IDE - that space-based stuff is kinda cumbersome and fragile even with a powerful tooling (

**Comment by ashnazg** [comment]
It seems to me that this all comes down to a decision on keeping the concept of "inline PHPDoc" or not... if we keep it, we can perhaps see if there are tags/scenarios where we *don't* want it available, though I can't think of such exceptions off the top of my head.

However, if the group thinks that implementing support for the "inline PHPDoc" isn't feasible/desirable, then taking it out of spec altogether is what we need to do.

@jaapio @mvriel did phpDocumentor 2.x get support for "inline PHPDocs" implemented?

**Comment by ashnazg** [comment]
Closing for now... will have to reconsider Inline PHPDocs as a standalone conversation later.
