### ISSUE TITLE
@link is "deprecated"

### ISSUE THREAD

**Issue by mindplay-dk** [phpDocumentor/fig-standards#104]
Why are we deprecating `@link`?

I often use it as a means of linking to a manual page or SO post where I found the solution implemented in a function, i.e. just to provide a link.

I generally use `@see` to reference a related method, or online when mentioning another method in a description.

I don't see why `@link` has to be deprecated? I think we should keep it for compatibility with de-facto standard php-doc, if for nothing else. The full description is there, in the spec, anyhow.

Also, as somebody pointed out to me recently, there is actually no such thing as "deprecation", since this is the first PSR. Differences from de-facto standard php-doc should be pointed out Appendix B, they shouldn't be fully spec'ed and "deprecated", I think?

Alternatively, since the proposed `@see` is actually *compatible* with `@link`, perhaps we could just include both as aliases for the same thing?

That would actually be my preferred solution, since:

  * it's already hard to remember which is which of those two - if you can use them both interchangibly, with the same syntax

  * nobody has to memorize or learn, they can just keep doing what they've always been doing (a lot of people will continue to use both out of habit!)

  * tools are going to retain support for `@link` for a long time to come anyway, even if we deprecate it

  * backwards compatibility with the de-facto standard and millions of lines of legacy code that is *never* going to get updated

  * it doesn't hurt

If you agree, we can just remove the section on `@link` entirely, rename the `@see` section to "`@see` or `@link`", and clarify this in Appendix B.

**Comment by jacobsantos** [comment]
Not sure if it gives more credence to your point, but I thought it was `@see` that was deprecated. Why would you deprecate `@link`?

**Comment by e1himself** [comment]
@mindplay-dk 
as you mentioned, they are kinda interchangable. It's hard to say when you need to use `@link` and when to use `@see`. So I think standard aims remove one of them, so next time you'll know you should use one that is left. 

I think it's good for standard to have less unneeded entities (especially duplicated).

**Comment by mindplay-dk** [comment]
> I think standard aims to remove one of them, so next time you'll know you should use one that is left.

That's fine in theory, but as explained, in practice, tools will continue to support it for legacy code (possibly forever) and therefore a lot (if not most) developers won't care or notice - they will continue to use whatever tag they're used to using in any given situation.

> I think it's good for standard to have less unneeded entities (especially duplicated).

I generally agree, but arbitrarily killing either one of these annotations for no real reason, seems unnecessary - there's no hassle or issue with supporting both as aliases, and no *practical* reason to remove them.

"I don't like having two names for the same thing" is just an opinion (and one that I happen to share!) - it's not a practical reason or a pressing concern that justifies a major break from the de-facto standard, and (I'm reiterating, I know) you can't get rid of it in practice anyhow, as tools *will* continue to support it, and thereby developers *will* continue to use both, because doing so won't cause them any problems.

One "soft" argument in favor of having both, is semantics: sometimes I just want to provide a "link", as a reference, other times I want to call your attention and remind you to "see" related documentation elsewhere. The words have different semantics - "see" is a call to action, and a "link" is just meta-data, which is one reason you can be pretty sure people will continue to use both, intuitively.

In addition, people who also write JS most likely use JSDoc, and are generally used to using `@see` as a tag to reference other types/members, and `@link` as an inline tag to provide web links - if we unify `@see` and `@link` we make it easier for everything to get it right instinctively. I think it's important to think about practical usability.

**Comment by mindplay-dk** [comment]
I'm in favor of a solution that enables everyone to get it "right" automatically, by default, rather than trying to punish some for getting it "wrong" according to some definition of what's "technically correct".

**Comment by Fleshgrinder** [comment]
Highly reminds me of the discussions on `<abbr>` and `<acronym>` in HTML that people always got wrong, although the difference is actually quite clear (for me) in that case. Despite that, `<acronym>` was dropped in HTML5.

It is out of question that we cannot deprecate stuff, simply because it is the first standard.

I do not like the idea of having multiple tags that simply do the same thing. Additionally, we do not need it for inline documentation purposes anymore, because you can directly use Markdown (`[PHP](https://php.net)`).

What to do? I would not define the tag at all in the standard and simply leave it to the tools, so they can decide. For instance, a tool that does not support Markdown requires the `@link` tag to generate hyperlinks, tools that support Markdown do not. Actually, tools that support Markdown would need to transform any `@link` or `@see` to a proper Markdown hyperlink syntax before forwarding it to the Markdown processor.

An alternative approach I can think of would be to define that any `@link` tags will generate a separate section (e.g. _Weblinks_) while all `@see` tags are going to another section (e.g. _See Also_). This is how it is JavaDoc and Wikipedia, so I guess this would be an issue to understand approach and gives them a clear distinction.

However, I would definitely allow URIs and FQSENs in both tags. In other words, make them interchangeable.

**Comment by mindplay-dk** [comment]
> It is out of question that we cannot deprecate stuff, simply because it is the first standard.

That is not the reason I stated - and I am not saying we can't deprecate stuff, I'm saying there's no technical or practical reason why we *need* to break from the de-facto standard here.

I want this standard to be easy to adopt - this doesn't help, and doesn't *have* to change.

> I would not define the tag at all in the standard and simply leave it to the tools

Which one? Both? Either way, that is totally unacceptable to me.

This is a simple tag, it's useful, it's widely used, it's easy to implement, and easy to describe in the specification. There's no reason to leave it out.

> An alternative approach I can think of would be to define that any `@link` tags will generate a separate section (e.g. Weblinks) while all `@see` tags are going to another section

Why are you trying to come up with even more ways to break from de-facto now?

If you want `@see` or `@link` to appear listed, you use them as tags - if you want them to appear somewhere specific, you use them inline. Nothing to learn, nothing to memorize, no need to break from de-facto.

I'm sorry, but I don't follow your train of thought.

We have an opportunity to simplify these tags *and* remain backwards compatible with de-facto - we shouldn't insist on changing things just because we can.

IMO, we need to stay on target, and come up with a standard that is going to be easy to adopt, easy to understand, and immediately useful. It's not like most people are going to read this spec and learn every detail of it by heart - most people, save for implementors, will glance over it and will expect most things to work the way they're used to.

Also, existing code is already full of mix-ups between `@link` and `@see`, because most people don't have any means of validating annotations - all of that code would now be *valid*, and everyone would already know how to use these tags.

Can we please try to make things intuitive and simple?

IMO, "technically correct", in this particular case, has no real appeal and no value, because it *won't make any difference* - tools already support it as-is and developers *will* continue to do it "wrong", no matter what the specification says is "right".

We might as well align the specification with reality when that is possible and doesn't get in the way of any new features or requirements.

**Comment by Fleshgrinder** [comment]
> That is not the reason I stated […]

Because it is mine.

> Which one? Both? Either way, that is totally unacceptable to me.

The `@link` tag, because the `@see` tag already does everything that `@link` would like to do. In other words, keep it as it is without the deprecation stuff and drop the section about the tag. Done.

> This is a simple tag, it's useful, it's widely used, it's easy to implement, and easy to describe in the specification. There's no reason to leave it out.

Actually, no. It casts confusion because people do not know when they should use which tag.

> Why are you trying to come up with even more ways to break from de-facto now?

I am not. `@link` creates a link, right? `@see` creates a link, right? Well, now we simply have define the semantics for them, **if** we want to keep both. I still think that dropping `@link` is the better solution.

**Comment by mvriel** [comment]
Originally I wanted to merge link and see into one tag. I now see that while the difference between the two is diluted they still have a different semantical role. Since documentation is about semantics and but technicalities I will revert the deprecation

**Comment by mindplay-dk** [comment]
> It casts confusion because people do not know when they should use which tag.

I don't see anyone getting confused - in fact, I don't see anyone stopping to think which one to use, they use whichever one they feel like in any given situation. That's sort of my point. Just make them both work the same - probably loads of tags, of both types, are currently technically invalid; make them interchangible, and you've fixed all of those tags without changing anything.

**Comment by Fleshgrinder** [comment]
:+1: for making them interchangeable.

**Comment by malkusch** [comment]
The current specification is confusing to me. I see `@link` deprecated in favour of `@see`. However @see doesn't provide an inline equivalent.

**Comment by mindplay-dk** [comment]
@malkusch that's what we were debating here, but the whole thing is sort of at a stalemate lately.

**Comment by malkusch** [comment]
The state of this issue is closed. So I assume it's meant to stay as it is. My point is, that's confusing as the current state suggest doesn't provide an inline alternative for `{@link}`.

**Comment by malkusch** [comment]
> I will revert the deprecation

Sorry, I just discovered this now. @mvriel could you please do that?
