### ISSUE TITLE
Inline php-doc definition

### ISSUE THREAD

**Issue by mindplay-dk** [phpDocumentor/fig-standards#105]
I'm confused by the opening paragraph in the section on "[inline](https://github.com/phpDocumentor/fig-standards/blob/master/proposed/phpdoc.md#54-inline-phpdoc" php-doc:

> Specific Tags MAY have an "Inline PHPDoc" section at the end of the "Tag" definition.

There seems to be some confusion as to what "inline" means - the term appears to be overloaded to describe two very different things:
1. "inline", as per the example in the opening section on "inline php-doc", where a description and additional tags can be _nested child tags_ inside a parent tag.
2. "inline", as per the "inline" variation of [@example](https://github.com/phpDocumentor/fig-standards/blob/master/proposed/phpdoc.md#86-example) or [@see](https://github.com/phpDocumentor/fig-standards/blob/master/proposed/phpdoc.md#816-see), which are tags appearing inlined inside a description body.

I think the term "inline" best fits the second category of tags, which don't have a parent tag.

I also think the term "nested" might fit the first category of tags much better, since these are really child elements of a parent tag and aren't "embedded" in a description.

It's also worth nothing (in the spec) that a tag can in fact _both_ be "inline" and "nested" - for example, an inline `@see` tag can be _embedded_ in a description body of a `@method` tag _nested_ inside a `@typedef` tag.

> An "Inline PHPDoc" is a "PHPDoc" element enclosed in braces and is only present at the end of a "Tag" sequence, **unless specified otherwise in a "Tag" definition**.

Maybe this ambiguous primarily because of the ambiguity described above, but it could sound like you're saying that all tags can be used inline in descriptions _unless specified otherwise_, which I don't think is true? What it should say, probably, is that tags _aren't_ automatically supported for inline use in descriptions, unless the tag definition explicitly defines it for inline use?

> The "Inline PHPDoc" element MUST replace any description that COULD have been provided.

I don't even know what that means :-)

On a related note, we support markdown, which would be a much more intuitive (and compatible!) thing to use in descriptions than inline php-doc tags. I'm not entirely sure where I'm going with that, but... inline links, e.g. `@see` and `@link` in php-doc, are generally written as `[text](link)` in markdown, so... we have some overlap there - although I do realize the spec currently _allows_ descriptions to be interpreted as markdown, already many tools are doing it, and we might as well adopt it full-on if we're going to allow it, why not? Perhaps if markdown could take over the role than "inline" tags fulfill right now, we wouldn't need both "inline" and "embedded" tags in the spec?

**Comment by Fleshgrinder** [comment]
I also think that the usage of _inline_ is ambiguous and I like your idea of using the word _nested_ for the (well) nested PHPDoc.

> The "Inline PHPDoc" element MUST replace any description that COULD have been provided.

This is regarding a situation like the following (I think or at least I understand it like that):

```php
/**
 * @tag This is a description, but this tag allows nested PHPDoc {
 *     This is the nested summary.
 *     @tag foo
 * }
 */
```

Tools have to drop the `This is a description, but this tag allows nested PHPDoc` part in favor of the nested PHPDoc.

I mentioned the Markdown and inline tag overlap in the other issue of you as well. I would also strongly recommend dropping inline tags in favor of full Markdown support (for summaries, descriptions, heck pretty much everywhere).

**Comment by mvriel** [comment]
> I mentioned the Markdown and inline tag overlap in the other issue of yours as well. I would also strongly recommend dropping inline tags in favor of full Markdown support (for summaries, descriptions, heck pretty much everywhere).

Not an option; inline tags have a long history and I am against breaking BC in such a way. Also: inline tags do stuff that markdown doesn't support.

**Comment by Fleshgrinder** [comment]
Not the `@link`, but the `@see` does and its inline version makes total sense.

You already dropped `@link` btw.

**Comment by ashnazg** [comment]
@mindplay-dk , please bring this up as a new thread on the FIG mailing list for discussion -- https://groups.google.com/forum/#!forum/php-fig
