### ISSUE TITLE
Include FQSEN in @ method when __call method is just a proxy to other objects.

### ISSUE THREAD

**Issue by GrzegorzDrozd** [phpDocumentor/fig-standards#112]
I was discussing this with @mvriel in emails (related to this pull request: https://github.com/GrzegorzDrozd/fig-standards/commit/6ddb8fd37a11fb1e343000446ecd7a68f7802c3f) but he was not convinced and he suggested that maybe community should speak up about this. 

So my proposition is to include class name in @ method tag in class when __call acts as a proxy to other method:
(example from zend framework)
@ method string url(...)
is in fact call to a method in Zend\View\Helper\Url. I think that if we add class name to that declaration we can improve documentation purpose - we can see what will be executed:
@ method string Zend\View\Helper\Url::url
This can also point to an interface method when called object is not found.

Do you think that we should include that ?

**Comment by Fleshgrinder** [comment]
I think that this is useful for some users, although I consider it super bad practice to program things like this.

**Comment by ashnazg** [comment]
For this edge case, I'd personally use an inline `{@link}` tag in the `@method` tag's description, and let that point to the other method that magically gets called.  As such, I'm -1 on this idea, though it does remind me that the inline `{@link}` isn't currently in the spec.
