### ISSUE TITLE
Support rebound closure scope

### ISSUE THREAD

**Issue by KorvinSzanto** [phpDocumentor/fig-standards#113]
In writing tests for abstract classes, it's often useful to stub abstract methods with working code that can access protected members. In PHPUnit, this looks like this:

``` php
<?php

abstract class AbstractFoo
{

    protected function doSomething()
    {
        return 'foo';
    }

    abstract public function foo();

}

class FooTest extends PHPUnit_Framework_TestCase
{

    public function testFoo()
    {
        $mock = $this->getMockForAbstractClass('AbstractFoo');

        $foo_stub = function() {
            /** @type AbstractFoo $this */
            return $this->doSomething();
        };

        $mock->method('foo')->will($this->returnCallback($foo_stub->bindTo($mock, $mock)));
        $this->assertEquals('foo', $mock->foo());
    }

}
```

Would it be useful to be able to annotate the closure with something like `@scope AbstractFoo` so that IDE's don't mark `$this->doSomething()` as an error?

**Comment by Fleshgrinder** [comment]
See #64 that could be used for this as well.

**Comment by TysonAndre** [comment]
https://github.com/phan/phan/wiki/Annotating-Your-Source-Code#phan-closure-scope is similar to what is discussed here

**Comment by ashnazg** [comment]
@KorvinSzanto , if you wish to pursue this further, please bring this up as a new thread on the FIG mailing list for discussion -- https://groups.google.com/forum/#!forum/php-fig
