### ISSUE TITLE
Are anonymous functions "Structural Elements"?

### ISSUE THREAD

**Issue by henrywright** [phpDocumentor/fig-standards#120]
Looking at the proposed [PSR-5: PHPDoc](https://github.com/phpDocumentor/fig-standards/blob/master/proposed/phpdoc.md), a function is referred to as a "Structural Element" and it's recommended that all "Structural Elements" are preceded with a DocBlock. However, there's no examples that cover anonymous functions. Are these considered "Structural Elements"? If so, how should we document these?

**Comment by Fleshgrinder** [comment]
It was agreed in other issues here that they are not, however, there are still discussions regarding documentation of them. For instance phpDocumentor/phpDocumentor2#1689 is related. Please have a look at the other closed issues here too.

**Comment by henrywright** [comment]
Thanks for the link to the interesting discussion on this. I'll close this to keep the conversation central to that issue.
