### ISSUE TITLE
Naming consistency

### ISSUE THREAD

**Issue by kwvanderlinde** [phpDocumentor/fig-standards#140]
It seems to me that `@return` should really be `@returns`, for consistency with `@throws` and `@uses`. I also find it reads better to have all these tags be in the active voice (e.g., "this function *returns* a `\DateTime`") rather than being prescriptive (e.g., "this function must *return* a `\DateTime`")

**Comment by zonuexe** [comment]
PHPDoc is derived from [Javadoc](https://en.wikipedia.org/wiki/Javadoc).  I agree with your opinion, but I think that changing tag names is not a good idea.

**Comment by ashnazg** [comment]
Too massive a BC break, I'm afraid...

**Comment by GaryJones** [comment]
I think IDEs (like PhpStorm) are permissive of `@returns` - may even be a setting somewhere for which to use when doing `/**[return]` to pre-populate the DocBlock.

I'd rather the spec just allowed for a single choice, or at least made it clear that one was preferred.
