### ISSUE TITLE
Add iterable pseudo-type

### ISSUE THREAD

**Issue by zonuexe** [phpDocumentor/fig-standards#141]
`iterable` pseudo-type is added in PHP 7.1.
see http://php.net/manual/en/migration71.new-features.php

I propose to add `iterable` into [Appendix A. Types](https://github.com/php-fig/fig-standards/blob/master/proposed/phpdoc.md#keyword).

**Comment by teohhanhui** [comment]
It should also be valid to write `iterable<string>`, `iterable<int, string>` etc.

**Comment by ashnazg** [comment]
I think this is legit...

**Comment by neuro159** [comment]
PhpStorm has support for `iterable` for about 2 years
https://youtrack.jetbrains.com/issue/WI-32378

as to type parametrisation... IMO this topic desires very special discussion.

**Comment by ashnazg** [comment]
PR #163 issued for this.
