### ISSUE TITLE
PHPDoc parser interface standard should be developed

### ISSUE THREAD

**Issue by panlatent** [phpDocumentor/fig-standards#146]
The PSR5 draft should cover how to develop the interface standard for the PHPDoc parser. The tool, including phpDocumentor, implements this interface, providing a clear and replaceable way for the parser user.

**Comment by tractorcow** [comment]
Given that psr-5 isn't yet formally adopted (https://github.com/phpDocumentor/fig-standards/tree/master/proposed), I still think it would be worth developing this functionality as an experimental feature.

**Comment by selden1992** [comment]
You are right, but the current project has not been submitted for 3 years

**Comment by selden1992** [comment]
It may not be maintained
