### ISSUE TITLE
About Tag Signature

### ISSUE THREAD

**Issue by panlatent** [phpDocumentor/fig-standards#148]
Hi, 

I am working on lexical analyzer to implement a PHPDoc parser. I do not understand the specific meaning of `meta-data` or ` Tag Signature`.

> The contents of a signature are to be determined by the tag type (as described in the tag-name) and fall beyond the scope of this specification. However, a tag-signature MUST NOT be followed by a description or other form of meta-data.

Follow this PHPDoc ABNF:

 > tag-signature      = "(" *tag-argument ")"

**Tag-signature should be between "(" and ")"**

For example：

```php
@param \Exception $e          Another parameter description.
```

Who is meta-data，tag-signature or description?

**Does the description belong to tag-signature or tag-description?**

Thanks！

**Comment by ashnazg** [comment]
@panlatent , if you wish to pursue this further, please bring this up as a new thread on the FIG mailing list for discussion -- https://groups.google.com/forum/#!forum/php-fig
