### ISSUE TITLE
@property-read and @property-write are missing from PHPDoc pre-draft

### ISSUE THREAD

**Issue by olvlvl** [phpDocumentor/fig-standards#15]
Hello,

I noticed that `@property-read` and `@property-write` are missing from the PHPDoc pre-draft: https://github.com/phpDocumentor/fig-standards/blob/master/proposed/phpdoc.md

Using `__get` and `__set` magic methods, it's really easy to create read-only or write-only properties. Consider the following code:

``` php
<?php

class Time
{
    private $id;

    public function __constrcut($id)
    {
        $this->id = $id;
    }

    public function __get($property)
    {
        if ($property == 'id')
        {
            return $this->id;
        }

         // we might want to throw an exception here
    }
}
```

`$id` can only be defined on construct and is _locked_ afterwards, while remaining readable.

I use this feature a lot in my framework/libs consider my [DateTime](https://github.com/ICanBoogie/DateTime) lib and its [TimeZone](https://github.com/ICanBoogie/DateTime/blob/master/lib/timezone.php) class, or my [Prototype](https://github.com/ICanBoogie/Prototype) lib.

IMO the `@property-read` and `@property-write` tags are very valuable and should be included.

**Comment by mindplay-dk** [comment]
Let's get this back in the spec, please - there's no reason to break the de-facto standard by removing a feature that is already widely supported.

**Comment by Fleshgrinder** [comment]
As I wrote in #37, sticking to the dash is inconsistent and should be avoided or you will face several discussions later (see PSR-2). I highly recommend the specialization usage. The result being `property:read` and `property:write`. This is imho the correct usage for it.

**Comment by mindplay-dk** [comment]
@Fleshgrinder The syntax isn't really the subject here, but the inclusion of the feature. (Feel free to open another issue, but I think you'd need a really pressing reason, technical and/or practical, to break from de-facto standard php-doc on this point.)

**Comment by olvlvl** [comment]
`property-read` and `property-write` have been supported by a bunch of IDE / Doc generators / Frameworks for quite some time now (PhpStorm, Eclipse PDT / phpDocumentor, ApiGen / Yii, ICanBoogie). Please use the notation already established.

**Comment by ashnazg** [comment]
These tags are back in the spec, so closing.
