### ISSUE TITLE
allow to hint "@deprecated" of a magic property

### ISSUE THREAD

**Issue by staabm** [phpDocumentor/fig-standards#152]
it would be great if one could hint via phpdoc that a magic property is deprecated.

I have more or less the same use-case as described in https://stackoverflow.com/questions/37554329/how-to-deprecate-phps-magic-property-in-phpdoc#37554478

atm it is rather hard to phase out a magic property as there is no tool support for marking them as deprecated.

**Comment by jaapio** [comment]
From a code point of view I totally agree with you that magic properties an methods are not a good idea. I prefer more explicit code.

From a more practical perspective I understand the request but I don't see any solution how to add a feature like this to the current tag. It is a very simplified way of defining an property. I think it should even be a single line? So also a - 1 for me.

**Comment by GaryJones** [comment]
-1 also. It seems a rather rare case, for it to be standardized.

**Comment by neuro159** [comment]
-1

**Comment by ashnazg** [comment]
Looks like a no-go.
