### ISSUE TITLE
Annotation for magic static methods available with __callStatic

### ISSUE THREAD

**Issue by lisachenko** [phpDocumentor/fig-standards#22]
Currently there is no clear way to declare a magic static methods available for a class that uses `__callStatic()`. Traditional `@method` annotation is parsed by IDE and listed as dynamic method, so when I trigger the autocompletion for `$this->` IDE can suggest me the name of magic method that is handled with `__call()`. When I use magic static methods there is not any help from the IDE because it can not understand that method is magic and static and doesn't list it for `self::` or `static::`.

My proposal is to add an extension for that via `@static` or `@static-method`. Look at the following example:

``` php
/**
 * Class Example
 * 
 * @method bool foo()
 * @method bool bar()
 */
class Example
{
    public function __call($name, $arguments)
    {
        if ($name === 'foo') {
            return true;
        }
        throw new \InvalidArgumentException("Unknown dynamic method {$name}");
    }

    public function __callStatic($name, $arguments)
    {
        if ($name === 'bar') {
            return true;
        }
        throw new \InvalidArgumentException("Unknown static method {$name}");
    }
}
```

Autocompletion for dynamic methods is nice, but the method `bar` is listed too:
![image](https://f.cloud.github.com/assets/640114/1186526/b50e0b1e-2306-11e3-9e57-b622831081ff.png)

For static methods there is nothing:
![image](https://f.cloud.github.com/assets/640114/1186532/1a9e5e20-2307-11e3-9816-f9c17faecb1a.png)

**Comment by aduh95** [comment]
It's been almost two years, and no solution has been selected. Can we implement one of those solutions in the PSR please?

**Comment by jimbonator** [comment]
Why did the above commit close this ticket?  I believe this issue should still be open.
