### ISSUE TITLE
Guidance on File-level short description

### ISSUE THREAD

**Issue by GaryJones** [phpDocumentor/fig-standards#24]
There's no guidance about the intent, and thefore what SHOULD be contained in the short description of a file-level DocBlock. The Short Description section says that

> A short description MUST contain an abstract of the "Structural Element" defining the purpose.

However, that leaves it ambiguous as to the RECOMMENDED usage for file-level DocBlocks in all cases, such as:
- File contains only a class / interface / trait (which would have their own DocBlocks and short descriptions - should it match?)
- File contains related functions (where a project might contain several files of functions).
- File contains unrelated functions (where a project might only have one file of functions)

Should the file-level short description try and summarise everything the file contains (often leading to redundant duplicate documentation within that file), or should it be the name of the project (so the file is identifiable outside of the project) providing more consistent file-level DocBlocks across all of the files in a project?

**Comment by jacobsantos** [comment]
In practice it does not seem like file-level phpdoc is all that useful. At most, projects should include `@copyright`, `@license`, `@package` or any tags that need to be inherited at a file level in file-level phpdoc. Projects should not include summary and descriptions in file-level phpdoc.

I think it is great that nothing is said in the PSR-5 text on file-level phpdoc. That really should be left up to the reader's coding standard. The problem with having any recommendation is that PSRs do not change and if your coding standard changes, you might end up not supporting PSR-5. So it would be one of those situations, where you say, "PSR-5, except no summary and description for file-level phpdoc." Which sucks.

I think in practice, very few files need summary or description documentation. At least in WordPress. It is troubling at times to come up with something, when the answer is that nothing is required.

**Comment by mvriel** [comment]
@jacobsantos I am not sure which point you are making .. PSR-5 does not require you to provide a file level DocBlock or, if you do provide it, require you to write down a summary and description.

**Comment by jacobsantos** [comment]
@mvriel I was answering the original poster, explaining why summary and descriptions for file-level docblock are not useful and why I support the decision to not include it in the standard.

**Comment by ashnazg** [comment]
This seems to have answered.

**Comment by GaryJones** [comment]
Note that `file` _is_ now included in the list of Structural Elements, and therefore the guidance of "MUST contain an abstract of the "Structural Element" defining the purpose", if the summary is present for a file-level DocBlock, (it is optional in this spec) applies.
