### ISSUE TITLE
@uses Files

### ISSUE THREAD

**Issue by GaryJones** [phpDocumentor/fig-standards#28]
The current example of `@uses MyView.php` is ambiguous. Can some clarification be given as to whether files used with with @uses are:
- path relative to the current file
- filename only
- path relative to the root of the project

**Comment by ashnazg** [comment]
phpDocumentor 1.x allowed for files, but I'm fairly sure they were only files relative to the project... actually, I'm thinking they were only files that were parsed by the doc build, too.

@mvriel @jaapio does 2.x still allow for this?  Files are not specifically mentioned in the 2.x manual page for `@uses`.

**Comment by ashnazg** [comment]
If this needs to be pursued further, please bring this up as a new thread on the FIG mailing list for discussion -- https://groups.google.com/forum/#!forum/php-fig
