### ISSUE TITLE
Constraints

### ISSUE THREAD

**Issue by mvriel** [phpDocumentor/fig-standards#4]
This is one of the items that I have not yet fully thought-through:

What we want is to be able to specify for a given type the constraint of its values.

Input and output constraints (i.e. `@param int{0..15} $byte`, or `@param string{CONSTANT1,CONSTANT2,CONSTANT3} $flag`, or `@param string{CONSTANT_*} $flag`)

More details from me follow later

**Comment by mindplay-dk** [comment]
I think this is an interesting idea, but not really necessary for the first version of the PSR.

Can we close this one and maybe reopen for discussion for a future version 2 of the spec maybe?

**Comment by ob-ivan** [comment]
Agreed to this being unnecessary. Let's do it one small step at a time.

**Comment by mvriel** [comment]
Agreed, closing this concept as it has no requests and I'm trying to tie things up for PSR-5

**Comment by mindplay-dk** [comment]
:+1:
