### ISSUE TITLE
Add variadics to type syntax

### ISSUE THREAD

**Issue by mindplay-dk** [phpDocumentor/fig-standards#40]
Looks like [variadics](https://wiki.php.net/rfc/variadics) will be supported in PHP 5.6 - the PHP-DOC spec might as well support this from day one.

Many libraries already implement variadics using `func_get_args()` so there was a need to document these already before native support for variadics - this is already supported by PhpStorm:

    /**
     * @param string ...$value as many values as you like
     */
    function f() {
        ...
    }

**Comment by mindplay-dk** [comment]
Hopefully this won't deviate from PHP 5.6 syntax when it gets added to the spec? I am documenting it already using the syntax above, and I have seen others doing it as well - as mentioned, it is already supported in PhpStorm.

**Comment by mvriel** [comment]
The variadics notation has been added or will be added according to the way php had provided these

**Comment by BenMorel** [comment]
@mvriel Still no mention of variadics in [PSR-5](https://github.com/phpDocumentor/fig-standards/blob/master/proposed/phpdoc.md). What is the suggested syntax for documenting variadics? There is an open discussion in the [PHPStorm IDE bug tracker](https://youtrack.jetbrains.com/issue/WI-29429) about whether to use brackets notation or not in front of variadics.

**Comment by Fleshgrinder** [comment]
Imho no brackets, exactly as the language treats it. Using `Foo[]` would suggest that you actually need to pass an array of `Foo`s but that is not the case.

```php
#!/usr/bin/env php
<?php

final class Foo {
    public function __toString() {
        return 'foo';
    }
}

/**
 * @param Foo ...$foos
 */
function list_foos(Foo ...$foos) {
    foreach ($foos as $foo) {
        echo "{$foo}\n";
    }
}

list_foos(new Foo(), new Foo(), new Foo(), new Foo());
```

**Comment by jacobsantos** [comment]
@BenMorel Work is being done in a separate repo that is forked from this one. I suppose the message is more that it was added there. This version is way behind the other fork.
