### ISSUE TITLE
ABNF features a literal CRLF

### ISSUE THREAD

**Issue by mvriel** [phpDocumentor/fig-standards#53]
The ABNF rules mention explicitly that the line ending should be CRLF but it must be CRLF _OR_ LF.

**Comment by Zegnat** [comment]
> but it must be CRLF OR LF.

I disagree, it must be `LF` to [comply with PSR-2](http://www.php-fig.org/psr/psr-2/#2-2-files):

> * All PHP files MUST use the Unix LF (linefeed) line ending.

**Comment by Fleshgrinder** [comment]
:+1:

**Comment by ashnazg** [comment]
I'm thinking we should go with the PSR-2 requirement of `LF` here, and have our ABNF follow it.

Ping @ondrejmirtes @muglug @neuro159 @mindplay-dk @GaryJones @mvriel @jaapio for opinions.

If we're all good with this, I can add it to my open ABNF PR or on a follow-up.

**Comment by ashnazg** [comment]
@neuro159 to me, it's just a matter of sticking by another PSR.  If IDEs have an available option to "enforce PSR-5" akin to "enforce PSR-2" to highlight things that are out of spec, then it becomes a _gentle_ nudge to update files as opportunities come along.  I figure many projects only gradually adjusted their code to fit PSR-2 back in the day, so having this "requirement" in PSR-5 will likely be viewed the same way.

**Comment by ashnazg** [comment]
If this needs to be pursued further, please bring this up as a new thread on the FIG mailing list for discussion -- https://groups.google.com/forum/#!forum/php-fig
