### ISSUE TITLE
@implements and/or @extends for traits (IDEs).

### ISSUE THREAD

**Issue by Fleshgrinder** [phpDocumentor/fig-standards#64]
This is something I was thinking about these days to post over at the NetBeans bug tracker. I often create Interfaces and provide a trait along with them that has a default implementation for interested classes. It's always a pain to copy over all the methods and documentation and keep it in sync. Two completely new annotations could solve this problem for generators and IDEs. The `@implements` is pretty straight forward.

``` php
/**
 * This is a simple Logger trait that classes unable to extend AbstractLogger
 * (because they extend another class, etc) can include.
 *
 * @implements \Psr\Log\LoggerInterface
 */
trait LoggerTrait
{

}
```

The `@extends` is mainly useful if (for example) an abstract class is the base for many other classes and one wants auto-completion within the trait for the methods that are defined in that class.

Both annotations would be magic annotations like the `@property` and serve no other purpose than providing dedicated annotations for a very special behavior. That would have to be limited to class DocBlocks of traits as well (they make no sense anywhere else).

**Comment by Fleshgrinder** [comment]
Closing, the feature is too experimental for PSR-5, please see phpDocumentor/phpDocumentor2#1689 and discuss further there.

**Comment by donquixote** [comment]
I think this does make sense to discuss here in the phpDocumentor queue, and it is not a duplicate to the other issue.

Personally I have not thought this through completely, but it seems a good idea.

Reopen?

**Comment by Fleshgrinder** [comment]
I want to wrap things up like @mvriel and I think that the two issues can be merged. However, this is of course open for discussion and I reopen it for further discussion. In the meantime, see the comment I just left on the other thread and note that I will not be able to answer you the rest of the day because I will not have Internet.

**Comment by dharkness** [comment]
:+1: 

I would like something like this for a different use case: declaring that a trait can only be used by a subclass of some other class. I use this when creating test fixture traits that want to pull in mock objects. This requires that the trait be used in a subclass of `PHPUnit_Framework_TestCase`.

I think `@implements` as described would handle this case, but the word implies something else, and `@extends` may be better for this case. Are you proposing both tags as synonyms of each other or only one form?

**Comment by Fleshgrinder** [comment]
I propose both. I do think that it is not really good style but it is simply useful and convenient to have and some people might even think that it is good. That being said, it might be out of scope for PSR-5.

**Comment by dharkness** [comment]
@Fleshgrinder Thanks. I agree that having synonyms in general should be avoided, but in this case I think it's warranted as there's enough of a difference in semantic meaning between the two (oddly enough given there nearly identical PHP-wise).

BTW, is there a document that describes what is in scope for PSR-5? I'm going through the document now and creating small grammar patches in a [branch](https://github.com/dharkness/fig-standards/tree/grammar-fixes) as I read it. Should I be making these elsewhere or within a ?

**Comment by Fleshgrinder** [comment]
No, there is sadly no such document and a discussion already started regarding the scope over at the PHP-FIG mailing list.<sup>[[ref]](https://groups.google.com/forum/#!topic/php-fig/e4_ttLCg8zg)</sup> However, @mvriel is currently not working on PSR-5 and thus everything is on hold.<sup>[[ref]](https://groups.google.com/forum/#!topic/php-fig/X2N17_qGKiI)</sup>

I and some other people believe that PSR-5 should be limited to the minimum set of tags that are absolutely required to support proper documentation of PHP 5 source code. This means that pretty much no new functionality should be added. We think that this should be done either in libraries (e.g. phpDocumentor) and IDEs or in a separate PSR.

**Comment by ashnazg** [comment]
If this needs to be pursued further, please bring this up as a new thread on the FIG mailing list for discussion -- https://groups.google.com/forum/#!forum/php-fig
