### ISSUE TITLE
Inline element definitions

### ISSUE THREAD

**Issue by mvriel** [phpDocumentor/fig-standards#7]
Suppose I have a webservice that returns the following JSON:

```
{id: 1, name: "This is my name"}
```

In my code this would (simplistically speaking) be expressed by json_decoding the string and probably returning it in a method. The problem
here is that the caller only knows that an stdClass will return but nothing in the documentation makes clear what it represents or what
members it has.

As such I propose that we add the capability to define meta-elements in DocBlocks to be able to return information on these stdClasses.

For example:

```
/**
 * @define myReturnedClass {
 *     @property integer $id
 *     @property string $name
 * }
 *
 * @return @myReturnedClass
 */
```

as is visible; the concept of Inline DocBlocks is reused here. The details of this new syntax still need to
be written and defined, the tag name and method to invoke a definition are not final and should still
be considered

**Comment by mindplay-dk** [comment]
Two thoughts:

1. I still think that `@typedef` should be allowed only at the file-level - optionally treating a class as parent/namespace is confusing. PHP doesn't support nested types, so this adds a new concept and learning curve. But above all, it's unnecessary - file-level typedefs will be quite adequate. Can we simplify, please?

2. Thoughts on allowing `@param` and `@return` in typedefs? This would allow us to define callback signatures, or even more complex signatures for types implementing `__invoke()` as well as other methods and properties. The ability to define signatures for callbacks is desperately missing for IDE support, I run into this often.

**Comment by teolaz** [comment]
Still opened since 2013? No way to simply solve this?
I'm quite interested in @param and @return for associative arrays...

**Comment by mindplay-dk** [comment]
@teolaz I'm pretty sure this PSR is dead.

**Comment by ashnazg** [comment]
I intend to resurrect it this spring, after phpdoc3 is done.

**Comment by Crell** [comment]
Wouldn't it make more sense to resurrect before you finish the new phpdoc version, so you can make the new phpdoc version match the spec?

**Comment by ashnazg** [comment]
Indeed... a better description of my plan is to get the CI of everything underlying phpdoc3 in place... then, while the others work on completing their own phpdoc3 stuff, I'll switch to the PSR5 WG effort.  I had realized that I wouldn't have the time available to do both at the same time, so opted for the CI first.  Once I get past the current blocker on that front (can't test new ReflectionDocBlock because PHPUnit requires Prophecy requires older ReflectionDocBlock), I'll start reading up on how to get the WG created.

**Comment by TysonAndre** [comment]
> I would really love feedback, be it positive or negative on this suggestion

For annotating arrays and possibly objects, supporting inline `array{name: string}` would be another possibility

I like the approach mentioned in https://github.com/vimeo/psalm/wiki/Typing-in-Psalm#makeshift-structs for these reasons

- It allows you to use the same syntax in `@method`, `@property`, and anywhere else that allows a generic union type.
- It allows you to write annotations on single lines, which is easier to parse (But possibly harder for human readers)

> However, we can provide a more-specific return type by using a brace annotation:

```php
/** @return array<int, array{name: string, type: string, active: bool}> */
function getToolsData() : array {
  return [
    ['name' => 'Psalm',     'type' => 'tool', 'active' => true],
    ['name' => 'PhpParser', 'type' => 'tool', 'active' => true]
  ];
}
```

Other thoughts:

- It would be nice to be able to indicate that inline elements are optional (e.g. `array{optionalField?:string|null}` or `array{optionalField:string|null=}` (Similar to JSDoc))
- It would be nice to support `stdClass{name:string,type:string}` or `object{name:string,type:string}` as well.

**Comment by XedinUnknown** [comment]
IMHO it could be useful to in general be able to define/document the structure of data, not just array keys.

**Comment by zonuexe** [comment]
Phan's array shapes syntax is reasonable and I like it, but the disadvantage is that this format can not contain documentation for array properties.

**Comment by ashnazg** [comment]
If this needs to be pursued further, please bring this up as a new thread on the FIG mailing list for discussion -- https://groups.google.com/forum/#!forum/php-fig
