### ISSUE TITLE
php-doc: mark methods experimental

### ISSUE THREAD

**Issue by white-gecko** [phpDocumentor/fig-standards#76]
Is there a way of marking a method as still experimental e.g. if the API is still under discussion? This would be helpful for framework developers to tell users of the framework, that a new method has a high risk of being changed in the future. Just like a `@deprecated` method might be removed in the future.

**Comment by Fleshgrinder** [comment]
:+1: I like the idea.

**Comment by jacobsantos** [comment]
I think you could just mark it `@internal` using the current spec. I would love to have this, even if it would be rarely used I believe. I think marking a class experimental might be more useful. I also think that anything that is not defined with an `@api` should be considered likely to change.

**Comment by white-gecko** [comment]
I would consider `@internel` more as the opposite of `@api`. Using `@experimental` one could mark a method as `@api` and `@experimental` to encourage developers to test the experimental method already, while there is no guarantee, that it remains as it is.

**Comment by Fleshgrinder** [comment]
See #114 where this idea is discussed as well.

**Comment by ashnazg** [comment]
I'm with @Fleshgrinder on this... I'd use the preleases, perhaps in combination with `@internal` tags to explain these "experimental" elements.  So I'm -1.

Ping @ondrejmirtes @muglug @neuro159 @mindplay-dk @GaryJones @mvriel @jaapio for opinions.

**Comment by ashnazg** [comment]
If this needs to be pursued further, please bring this up as a new thread on the FIG mailing list for discussion -- https://groups.google.com/forum/#!forum/php-fig
