### ISSUE TITLE
Support overloaded functions

### ISSUE THREAD

**Issue by e1himself** [phpDocumentor/fig-standards#82]
Hi there! 

I'm new here (just found out about this PSR proposed).
I want to mention that there is a feature that PHP already uses, but cannot be documented as well.

It's _functions overloading_.

There _are_ standard functions that act like that since at least 2000s. But we have no way to document that.
Consider _parse_url_ function:

``` php
// Single argument usage
parse_url(string $url): string[];

// Common two-arguments usage
parse_url(string $url, int $component): string|null;

// Retrieving port returns integer (if present).
parse_url(string $url, PHP_URL_PORT): int|null;
```

Though I think dealing with the 3rd case (when you need to match argument value) is out-of-scope for current issue, we can handle first two.

Suggestion:

Add **@overload** tag with inlined meta data for valid function usage. Tag can be used multiple times.

``` php
/**
 * @overload {
 *    @param string $url
 *    @return string[]
 * }
 * @overload {
 *    @param string $url
 *    @param int $component
 *    @return string
 * }
 */
function parse_url(string $url, int $component = null) { }
```

**Comment by e1himself** [comment]
Also I wrote an article describing PHP code documenting issues valuable for me.
Maybe it can bring more light to current issue: [Definitely Typed PHP](https://medium.com/@e1himself/definitely-typed-php-9c5c41d2c810)

**Comment by mindplay-dk** [comment]
> There are standard functions that act like that since at least 2000s. But we have no way to document that.

:+1: very good point.

For some reason the name `@overload` doesn't sit very well with me - it seems to describes the *action* of overloading, which in my mind is the *result*, as opposed to describing what the alternative method/function signature *is*. I don't have a suggestion for a better name just yet though...

**Comment by ashnazg** [comment]
Not really on board with this idea, as it seems to want to take a function that's very loosely defined with regard to its args/returns, and try to wrap an assortment of more strictly defined things around it.  I'd rather adjust the code and use existing doc options.

Ping @ondrejmirtes @muglug @neuro159 @mindplay-dk @GaryJones @mvriel @jaapio for opinions.

**Comment by jaapio** [comment]
However we both agree that this is not really a good way to write your code. The php internationals do contain methods like this.

But I think we can just support this behavior with the `@method` tag. I don't think the method name has to be unique, or does it?

**Comment by muglug** [comment]
I'm not sure it should be part of a doc format when it's not a very PHP-ish way to write code (at least one maintainer thinks userland support for overloading will never be a PHP feature).

**Comment by ashnazg** [comment]
If this needs to be pursued further, please bring this up as a new thread on the FIG mailing list for discussion -- https://groups.google.com/forum/#!forum/php-fig
