### ISSUE TITLE
Clarify the "function" structural element definition

### ISSUE THREAD

**Issue by EvgenyOrekhov** [phpDocumentor/fig-standards#83]
https://github.com/phpDocumentor/fig-standards/blob/master/proposed/phpdoc.md#3-definitions
Does the "function" construct of the "Structural Elements" collection include anonymous functions (closures)?
The question originated at https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/1300

**Comment by ceeram** [comment]
It does not include them, i had consulted @mvriel about this, here is a transcript of the conversation:
```
Ceeram
21:09 howdy, i got a question about psr5
21:09 https://github.com/phpDocumentor/fig-standards/blob/master/proposed/phpdoc.md#3-definitions
21:10 it states functions (including methods), does that also inlcude anonymous functions, for instance as in this code example: https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/1300#issuecomment-121673175
21:11 would that be a correct or incorrect usage of phpdoc, the orignal example in the issue is imo incorrect, as it the phpdoc precedes the variable, not the anonymous function, just in doubt if the linked code would be correct use of phpdoc
mvriel
21:11 Ceeram: I didn't intend it to. Closures are a bit of an odd case. Also: if you need a Closure to be documented you might need to move some stuff elsewhere ;)
21:12 Ceeram: a closure is not a structural element in PHP, it is not part of a structure so yeah .. that also makes it harder to find
```

**Comment by EvgenyOrekhov** [comment]
I think this is a mistake. But anyway, it has to be clarified in the document.

**Comment by mvriel** [comment]
@EvgenyOrekhov you are free to add DocBlocks with your closures, there is not going to be a section in the PSR that will forbid that. It is more that I haven't seen this in use in the real world and I think it would be good if this evolves first before we try to capture it in PSR-5
