### ISSUE TITLE
Feedback / Proposals

### ISSUE THREAD

**Issue by Seldaek** [phpDocumentor/fig-standards#9]
Hey, here is some feedback, because while I love the idea of standardizing this all, I think the proposal isn't quite pushing the envelope enough ;)

- `@type`: can we please omit $varName when we annotate a var? This is pointless repetition AFAIK and leads to out of date documentation.
- `@param`: same thing for $varName, and possibly even omitting the param type if there's a type hint. If that's syntaxically confusing, maybe `@param & description` or some other magic syntax would make sense to avoid repeating the type hint.
- Regarding `@category`  and other deprecated tags. I would just remove them from the spec or just mention them in an addendum note. They're history so let's not clutter the spec with them.

Overall I think what's important is to avoid repeating whatever is in the code in the docs. Docs should complement the code, and the tools should infer what's possible from them. If writing docs forces you to repeat what's in your code, you tend to do it less, and if you do it tends to get out of date/sync with the code. We should strive to avoid that.

**Comment by mindplay-dk** [comment]
@mvriel I just returned to this issue, and I am still firmly convinced that you're wrong on this one.

I don't see a good reason to break de-facto standard php-doc on this point - there's a trillion lines of annotated php-code out there that would be rendered invalid by this change.

A much more reasonable BC break would be to simply drop support for this:

```
/**
 * @type string $foo
 * @type string $bat
 */
public $foo, $bar;
```

I don't see anybody using that in the wild, and, although I realize we're not obligated to align with other PSR standards, by now, PSR-2 is the most widely accepted PHP code standard, which (for properties) mandates:

> There MUST NOT be more than one property declared per statement.

Now, if you insist on supporting annotations for multiple-property declarations, we can easily explain in the spec why names are required for multiple-property annotations, but are optional for single-property annotations. That's easy.

Forcing repetition of the name in a property-annotation, which can only possibly pertain to one property, doesn't make any sense.

Forced repetition as a means of name validation isn't a reasonable argument for such a massive break with de-facto standard php-doc either. If you think that's good practice, you can do that as part of your own code standard - but it's based on opinion, not on the practical needs of everyone, and therefore not something we should impose on everyone, and not a good enough reason to break from the de-facto standard.

I'm fairly certain that most people would never even notice this change, unless you call it out in bold, red letters - a lot of people (myself included) would continue to omit duplicate names, and I'm certain IDEs and other tools would continue to allow it. An IDE, for example, would immediately have much poorer support for existing PHP codebases, if they were to ignore then-invalid tags without the duplicate name.

If duplication works for you, go for it, but let's make it optional, please?

I'm happy to PR and write up those changes.

**Comment by mvriel** [comment]
Please reread my comment above yours:

> Nonetheless, the recent changes that I made to the PSR allow the omission of the variable name for properties so that you can use that style if you'd want to.

I'm closing this issue now with the following conclusion:

When documenting a block of properties the DocBlock should precede the compound statement and mention each property using an var tag. It is recommended, but not required, to provide a variable name. If a variable name is omitted then documentation errors are more likely to remain undetected

**Comment by mindplay-dk** [comment]
> If a variable name is omitted then documentation errors are more likely to remain undetected

Er, no.

If the name is omitted, then documentation errors are more likely to occur *if* and *only if* you use multiple-property declarations. Which almost nobody does.

If, on the other hand, you *don't* use multiple-property declarations, repeating the name only *increases* the chance of documentation errors - e.g. names not matching.

I don't even understand how you plan on handling those errors in the first place - if I use mismatching names, which one is going to count? Are you still going to count the type as being applied to the property if the name doesn't match? I can't think of any meaningful way to handle these errors.

Almost nobody repeats names today, and I don't know why they would. I think it's your very personal opinion that these names should be repeated, I don't understand why that should be "recommended".

Why would we be optimizing for the recommendation for the multiple-property declaration scenario? Almost everyone follows PSR code standards - hardly anybody ever uses multiple property declarations.
